---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-token
  namespace: roboshpee
spec:
  encryptedData:
    discord-token: AgBWBoTqnw5cLym/GqrGhHma4GwyvXkdtGxj88uh/700Li1kePtMCvsjwA9hHkqOYmVuL2hymgHUVz8xUdQ5lxm6MsunjkohaslCYtZVf+zD7HOr9Tnbxez8aQvk7TDj6jKz6sRn1g8UJBeqiK11e60oxGDSN9hGufz3oOmbvW/t3PtQNVd9iPrULgtsXJ5vtqiXsVGJ55z1F9QV+mC9fCHCMsWymybDS4zS7czFD2wsTU7Zmlyx51LiEp0Szhi59rEcZNY09u3BHunfc6Y4hX4nIMxFEQIK633FVjr1Xkf4FljmXJ9gkIxXFuEEkDCyaAJomPspSdfI44weyhpXG3+VQCc5DzZzz6jwG8ohO9BdrpfN5KhP5EWxA2UBpYT0rsb7fswwgjBHVaEvhDCr3qEf6fFYe64rELd+ulCvnzLauQcC8nNP0RsJJPc11VDiDi6YKwppdg5rvkp575ml0fUz0bMVhBKrFCj/7tj+3P36YIAjDjXQVh/btAUS4WzsHhyOuLnDdMUFqEh8HPPkbPmClNGomnrmFS249Tjw/rycc4V/YY8n7KN7zMLJiTPgW8BnGO9ZgXGjuUQHXr2CPyxdMpTaqTszjvI0CkiVgSOCG7B2H8mGRiEOFCCdoQV5SR0xn2KUsdp3owbMMk/8tdENwq/stW/ajuYV0lK/KQJGwBx9Gb0TS+OrcMMIZCUZs2b46O2rBpzk3y/7fUKfAFIO3TYliLlcnOBFBCUEfmAu2ITmCyjfDKVfiYXZAkatYOPsQpy3oQNxekz2BeDiitUpFqq2/qyP
  template:
    metadata:
      creationTimestamp: null
      name: discord-token
      namespace: roboshpee
