# vim: ft=yaml.ansible
---
- hosts: rpi-1.kgb33.dev

  tasks:
    - name: Load DISCORD_TOKEN from SOPS
      community.sops.load_vars:
        file: ./files/roboshpee.yaml.enc

    - name: Start RoboShpee
      community.docker.docker_compose:
        project_name: RoboShpee
        definition:
          version: "3"
          services:
            roboshpee:
              image: "ghcr.io/kgb33/roboshpee:latest"
              network_mode: host # Required b/c PiHole is on the same host
              environment:
                DISCORD_TOKEN: '{{ DISCORD_TOKEN}}'
              restart: unless-stopped
