# vim: ft=yaml.ansible
---
- name: Initalize Control Planes
  ansible.builtin.command:
    cmd: >
      talosctl apply-config --insecure
      --nodes {{ ip_addr }}
      --file ./files/controlplane.yaml
      -p '[{"op": "add",
          "path": "/machine/network",
         "value": {"hostname": {{ inventory_hostname }} }}]'
  when: k8s_role == 'control'
  delegate_to: localhost

- name: Initalize Worker Nodes
  ansible.builtin.command:
    cmd: >
      talosctl apply-config --insecure
      --nodes {{ ip_addr }}
      --file ./files/worker.yaml"
      -p '[{"op": "add",
          "path": "/machine/network",
         "value": {"hostname": {{ inventory_hostname }} }}]'
  when: k8s_role == 'worker'
  delegate_to: localhost

- name: Wait for Talos GRPC to come online
  ansible.builtin.wait_for:
    host: 10.0.0.116
    port: 50000
  delegate_to: localhost

- name: Bootstrap etcd
  ansible.builtin.shell:
    cmd: |
      talosctl --talosconfig ./files/talosconfig config endpoint 10.0.0.116
      talosctl --talosconfig ./files/talosconfig config node 10.0.0.116
      talosctl --talosconfig ./files/talosconfig bootstrap
      talosctl --talosconfig ./files/talosconfig kubeconfig ./files/
    creates: ./files/kubeconfig
  when: inventory_hostname == "teemo.kgb33.dev"

- name: Wait for cluster to compleat initalization
  ansible.builtin.wait_for:
    host: 10.0.0.116
    port: 6443
  delegate_to: localhost

- name: Install Cilium
  kubernetes.core.helm:
    #  helm install cilium cilium/cilium \
    kubeconfig: ./files/kubeconfig
    name: cilium
    namespace: kube-system
    chart_ref: cilium/cilium
    chart_version: 1.13.1
    set_values:
      - ipam.mode: kubernetes
      - kubeProxyReplacement: strict
      - k8sServiceHost: "10.0.0.116"
      - k8sServicePort: "6443"
      - securityContext.capabilities.ciliumAgent: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
      - securityContext.capabilities.cleanCiliumState: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
      - cgroup.autoMount.enabled: false
      - cgroup.hostRoot: /sys/fs/cgroup
      - hubble.listenAddress: ":4244"
      - hubble.relay.enabled: true
      - hubble.ui.enabled: true
