apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    cf-token: AgC1/sY7nW7mZuLvka+CHlXl4H43D41aTQIc/p6P+oaAliWURvcesofBCgt2JsdO0lin9vOxiNyI7IkMFJe0pztaEM7+SpW91B2kJJ/WuMW8T6XpwhWZq+0cjLtehJF/BsnhAZ87H5r6UA2yMHi+J0DZjHBXOSR6fpOZIdpLDPu/PcJc/XBxGxZKQM8Hj0TJ29abjrxnY0xc/UuxTVfMdPP41JqGYkasE+xTdDIzCuNrRbyHS9Waw9yZEsUdszAvdnW00p1t2OhaPwsCwny5iRB5P6ublkSOEskmKlPss0g+lNqwXznP9hB1MQWiq5TEZyuzDDkStTksiI2ruFJHKMXrfHhwTgp9ba6ReFwF4cDrEYgdaVypJveX2Do1Hh9/Klf9fD/K2vkjWxsPnhv3HdqQuf05rOyjqbh8I9nOwVt8kh6fU+f6wqxvuzpDFwc2P00YAQeJ7Fls3v9uzjtBxBQ9fUjYtuFpebS04wC6Y1UzOoY2OSuw+NAENqMfiriFq8GCANAN1HGB9suSOIVY9JBnEqitREDJt/x+sxK1S93KvFrTUl/VDh15JK8VkZ/QnfxUjEjPcXan2NNgyDk8ZMPzoPM3gIAN4q5bb5F82L4uxKGOdf43Cc30HJy8cJYdbuvIAp2pGHIAX7YmPVEJswL7l2G5jU+Y+dG/MJnOXwnGg1DLDx9A89iTSv/BtuWS6YY6/5b0bQWlp6PIT9c245kZw1wyFQatizGtLosgZA7EoTiUFuJz0uSc
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik

