apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    cf-token: AgBRUiy+Nk3LOF+I/6IhtXqg4JPZSMwAUQBflUpPdLHNpB7b5wElV4TEjQYhvDWYY1dX+Wctsd8M9Xvo/pTRu8WSveLFPYS/tFRtOntjLzhteGrOw1SBCSQidlH2JYbf249+PZwp4p858whaK3yt761yk73Ww/sWDE68RmwVPcY2Thht3HN9OO5UWjq/cHCaswYUP4BjX3Lxfo8oWf75PPeuhASpnd3e+3zhTeWJuAPGNgiuSyf4YBHSl8GwjnixtS5UDk+PIqPiQANweRxVYJQhW8KGik81W75gfjQe8dgBt2cP1tEGv45U/Lz3gnJNRmJiVzhRdEI6ErWp4eDILcSRR1IrAY/7ME7/DngF/kMWyaIAVbzvcDnhuT6hOE8r1vvBS2AmXK7UAdFAURyg+5pIpCRpJTNf55xTzhHQGpH9od4ZnHHVZqfF05s5TA0nCDI7oQ7iw4uD49kE4yqaDQAqP9buWEZg7lUk9LH6RRSnKtQQ6faJsXfP1pbDHrrLjdcmj9Q1pfJyVVz/iEMsz455Psdu64IwOsjx9AlR+6Eja+hvRZr7cI5IER1D2SQbvR/0FPFZtj8Ay0qbXky0X2pixB8c+k6jb4af+nRZqNTMmhyuPdindth4RO5+u7gVB32a7d0fQgDE0JtGAKgOF5pC6jhkJpKiCF+klALS5VbKkAVPdvFjPPicRwSo2zr7ScsvWdjkc4U3yGH+cGBAKm+Ycy2XdRweFSu91zeNpMSz0Up3X3q9nDLq
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik
