apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    cf-token: AgAu/CNeQHPKRi/UFZibeErmNP2qpFiJaQ1coSp23TBkgM67b5DEtRGRoRfiyn0CxOehsxw4jtdFlpKlX4DW2RY8UpcOCmFgz51v5b3tnNZQypeNJQeJHMwPMhSWPda45YjBYPr71WeHiwXRfacE6YeSD+U28/Uu5A8Di8/GLMJZD3kSmhEr4p7ty4Kb06uB1hqLnAAVpel0LS4U8n3Kdc3BNtAX/sGJLZRWJACg2UYx+z8qAfZq3tOO+q137KHKjxwPbv9Gp16aMeZ3W4twoBD/IIKUxnC1ko5EJUn/GXuJG03JBGhV6QUL1vO7L7kLSWfnYvo7/Kvjo4T9aX71H4QoWyU8KgErHlK9+BLVvJZPp5zWlzYjLoF/xL5zAJQzuB7Topib7WKAyuTKulMjoKvQjIQhAC7hxfwamA5f8LVq5bZOxTH5TlNnWhps/fk/yWy8LM+Fw29promCZr+MLA9aPPB4neTYEtbR05Rbi40nLLxElCERqWQNNDgpEaB2Q4HqN59wMFJ1dsf+iPvKKe0Ixaw985iDB8J2Z57MC6bqucaD9eM5AWwXrv5KpRcPuHjfT2bIFQIfI8+cdG7l3r3LeXFbL1AcSbRoetF0Sf5rAz74TWlZRABYvh0r3l5ezibgLE91vmRnUCLSdX9HlacjM2n0whp4xSUEeoR8dLsQFBLEuxgTyclj50VL7h4aBFaAdFu5u8VAruu9LUUtvACZf8JXRnSo0Yj2n8XR9foDYKngKGx2Iw/b
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik

