---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    cloudflare-api-token: AgCmZk15phXbbPZAj+GqnkGoRRAkOm8A/Sen7UDTwU7pp1bq/rIKuSR8XnvdP9wefxkC3y9wTHi8p6fYvZCoTK5iNYffG68ogPfjKLGsPGBXaRac7JPHYq+PHJqqga3YA7iqt8wXnvvd69cwYbavP+Xrmg9V6F/BZEy622GloV3xaNiZkHQMTdcmYXay7P56IiX30S/21E9NNoP55egGurZtbyw1SOAmo8sW6oWamIxNoEJwGR0ug+VTACJc9k/WNHfMEL3zfFKCrvr7kCR2FoNsGm3mjM9Pkeh/ubQPeElaj27pI8a6vEA0l6BsLRrNMr8ODxurDbjcqZFmHM3mEWarSj899lX6eK0QJ5Aals9PDtXLmstYuzfQXqu0EnSySd4lz2Eli5NXzt/x5Vi3JuHRINdXSByPLFhANZvLcK/yallrDvOK9gaukonguR7qWaPJAoMixv4pSMyShMW65BVALX2rfmQ0gVQ/R5pyuVxCA2zdWwtNiUosweQqS1vyBpsHQE5emk38CFu9Vb2ijXhQ5zqTTGH7Yq7nQKE/KJM/dd40sZWudMmz0jSDoHjhx3hT+n9p4FGhRR6uF+c7Yk7m0/jsFEvzgkgNTTxbIMb/57fzsNLVVTB54jjxerBQQxvzaKrhiIz56IrB1giUW1pdsL1uX0ikI+wTqLmc4H1+UNnnNBcPrbQehkObZn31wNMBjXPe74IJKW2+80QrAXAf79t4HdxWwdm7te/0v+9ZBtb8bqOM5H0Z
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik
