apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    cloudflare-api-token: AgAjwZBP3xmbd6xNBQHNUAaOPCpFvq4/TaoRsekAKWWRZKCObg3QHFGl7tZ7B7QQQGJRPysSDuXbVb5q1LlEO0QfpxsQ1dqz3u2rJAmSVHhsyYlzpkh/TVUBjnl69YslWZ/6yerKBG4sSdQ4LbiPhYzUOFCQWLdRl1CaxetePACuAAx5kSTUeUAFxJsPmbhTIbEAj2J2V4IzGYHnreCn9aci+qqNtw2wlhDjg035tAvajQBjAUNEW5liM9Gir+SUsOdEFMqu8uNVfdtLqLAklFfubK/4YosEkbPvQt62HBP1qngn2geovtCSr+7GZdsbZU80HUCai02BvS/BzsSUaWmKzKyyrynyOTtX2zaSKo1VgmX6ZzIdWVBNo5WVGJX6Dqv9EZzeLIIT2z4dUr+DblgyjVU99dUJACkHQxIeIQzMY6os3QZVPoATw+9CNg4/skQ2MtFN1ur34P3nQzTWksao7PZk1XKY7rSPd3iDIDcd7SaIpGxn7U2BAsEGVpaxg8bEc+lLPy31Va/uXFRrtsRzG4Sm6EhXXOp2Cb0vV47cdDULNRKyxQQ6iuUtWeG4sHw6D1UvS3YJDTImrfdGyoaAXoPFOz6x6CxTO0SSOW/PBcOyx1YFKvOW7mUUrSl4y55Ar85cvEwbkRhpVlHo8Bl5FkotMv4cKrzP1hcQg5WOVIVEle5LlygYaZBAVpCy8h+73sHf1+JecJKuZqENDJhlRG2usEjjNyeDJW9YLaj6yO4+bZC63gA3
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik

