---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    cloudflare-api-token: AgBe76DoO4fmkCral8i5DRfJdmetGCH13231zI66sk+7vik40v41R7N+CkdRI5LXFjgCh6FLo6bQ1uu7AXbLM29vYh9INfi38U3uvH+3ImIZzDJRmQo0cuQLfBOQN1zNhpkpiBnz2w7J62vpc+Wpemn9OrlzxIwisE16Cvy7JKd0TXftnrnQ9mhGbtKaAop2tZJgFwU31M65WI4K7+bk6QwIBubIzeZu3YD9o30pdaC+ItGd62LzkWq7briACqlUwf0JCzqQ3ICyI6nSqV9xtyas6kZUtGLfHV8luSz+j+m3FKLs4vU47RJYnpZ7l6R/6Fj9zRiOf2zf7+A6rLb9xHNchqKU8BY3ENaLqetjmUm/72NqYCqmqcPmsXEWBq+Bf0DE3UiOht+BceFoXp+i6cplCVzhywhmFrbai7pmGl5AwdgpJ89wD4fTjIlD8QzH5rv0lT2bYe6cOXCsAMeiq0Ot41zKUQcPG1hNiGdKd07Pn9sfYpp7RV3dkPxKXyKnOM7SwGLOF5zlFtRA2hAuCrGurlYlDyKaIGeddiYu0kbjGzBu6nSOCFqKO+9R+84J+ziupQI2ufr7/wkLN4ykIzFMCfrOnuMbGMdUbPSM/IDKGBP/B7XKI/GjA2V1edFbrYKyPRhTa8cr5MjrBaQ8ebTFTGfkiIy5JDIHgW9nzcVbXKVcQ5g89WNWZApdtzKy2ielQXroAoka8EeiDVTqdi77/ujHkTSdDxTO2wa53nrr37iG+KCW2MiT
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik
