apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    cf-token: AgAJk9jwFjiq9oek0O4IoQVZWJEW4gsrGMf7h+9p9in8Gl03zr7576tWbp2P4Yy4DOKdqULzK7SOc3zfF+LBL8E8JSIFCvpjvFo+ti9NbV+wdrY8+t4ZCbVCBHzToCooLrYtFIcYvVAm6xbkn3fqTKfn45FEMM9XufacfPmY5O1G4aeBdGF/v0XzAF3cqPiJQUDplL1/OBYzjxyEM1CU7iHxcLSiGAX6xx+8jhZKvghvj3XjyVFBcEmH5VukeWi7Vh5ktwuPIzPXKr5W0VTPbhQNzppNWh5gmdouSpoLlI51gtRxlBWmjthoM3uMICc5WQLzOC1XAaknd6p8INLSno4C+2sDEdqTv4d+X4OOWoxTRgNsZcJmtKSpp3P8TotLtErhDRwWbn6dBqZKMUpW8d4paY617BgOreRJR77iM9qFIXSNMlQEcEpEJYaSndKTmN5YEIdJbkHWIqvK9DO/CxZ7tXltsUqXLUhC9j2PF9xVahPhqmNcCif++S/VFoLllf2AJAPun7zOFGyzObqPxuybrs8a6ns5HcmKOpmMtrbpfj5q4ktyAnAhEGsJMCnmMEWNkEMUmM60acZCEXq6LNX+QiT/BhLYhb0rxxV2dQWCFqj/UNfrf+V2x+CX3a03Wuvtg2tlEQ/G3SSPG/rIBh1vGNSxLP+pVEFudDV2rAdv4zCgxdCVH4cA8HXnnrUnDSebnTriAvhlHWLOZ18GeXu3wir9xr7IFkmBgIcDtpUDcaAgpte7Fo2L
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik

