kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      volumes:
        - name: cf_token
          secret:
            secretName: cloudflare-api-token
      containers:
        - name: traefik
          image: traefik:v2.9
          args:
            - --api.insecure
            - --providers.kubernetesingress
            # Redirect all traffic to TLS
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --entrypoints.websecure.address=:443
            # ACME Configuration
            - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
            - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.letsencrypt.acme.email=keltonbassingthwaite@gmail.com
            - --certificatesresolvers.letsencrypt.acme.CF_DNS_API_TOKEN_FILE=/letsencrypt/cf_token
            - --certificatesresolvers.letsencrypt.acme.CF_ZONE_API_TOKEN_FILE=/letsencrypt/cf_token
            # Staging LetsEncrypt Server
            - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
          volumeMounts:
            - mountPath: "/letsencrypt/cf_token"
              name: cf_token
              readOnly: true
