apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: traefik
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.8.138

spec:
  type: LoadBalancer
  ports:
    - name: web
      targetPort: web
      port: 80
    - name: websecure
      targetPort: websecure
      port: 443
  selector:
    app.kubernetes.io/name: traefik
