service:
  enabled: false # Define services manually
certResolvers:
  letsencrypt:
    email: keltonbassingthwaite@gmail.com
    dnsChallenge:
      provider: cloudflare
    storage: /data/acme.json
persistence:
  enabled: true
podSecurityContext:
  fsGroup: 65532 # matches group for the initContainer below
env:
 - name: CF_DNS_API_TOKEN
   valueFrom:
     secretKeyRef:
       name: cloudflare-api-token
       key: cloudflare-api-token
 - name: CF_ZONE_API_TOKEN
   valueFrom:
     secretKeyRef:
       name: cloudflare-api-token
       key: cloudflare-api-token
ports:
  lan-web:
    port: 9080
    exposedPort: 9080
    expose:
      default: true
    protocol: TCP
  lan-web-secure:
    port: 9443
    exposedPort: 9443
    expose:
      default: true
    protocol: TCP
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.k8s.kgb33.dev`)
    entryPoints: ["lan-web-secure"]
    tls:
      certResolver: letsencrypt

# Fix ACME permissions before traefik starts
deployment:
  initContainers:
  - name: volume-permissions
    image: busybox:latest
    command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
    securityContext:
      runAsNonRoot: true
      runAsGroup: 65532
      runAsUser: 65532
    volumeMounts:
      - name: data
        mountPath: /data
