ports:
  internalWeb:
    port: 9080
    exposedPort: 9080
    expose:
      default: true
    protocol: TCP
  internalWebSecure:
    port: 9443
    exposedPort: 9443
    expose:
      default: true
    protocol: TCP
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.k8s.kgb33.dev`)
    entryPoints: ["internalWebSecure"]
