service:
  enabled: false # Define services manually
certResolvers:
  letsencrypt:
    email: keltonbassingthwaite@gmail.com
    dnsChallenge:
      provider: cloudflare
env:
 - name: CF_DNS_API_TOKEN
   valueFrom:
     secretKeyRef:
       name: cloudflare-api-token
       key: cloudflare-api-token
 - name: CF_ZONE_API_TOKEN
   valueFrom:
     secretKeyRef:
       name: cloudflare-api-token
       key: cloudflare-api-token
ports:
  lan-web:
    port: 9080
    exposedPort: 9080
    expose:
      default: true
    protocol: TCP
  lan-web-secure:
    port: 9443
    exposedPort: 9443
    expose:
      default: true
    protocol: TCP
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.k8s.kgb33.dev`)
    entryPoints: ["lan-web-secure"]
