apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: traefik
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.8.137

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: internal-web
      name: internal-web
    - port: 443
      targetPort: internal-web-secure
      name: internal-web-secure
  selector:
    app: traefik
