apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: traefik
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.8.137

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: internalWeb
      name: internalWeb
    - port: 443
      targetPort: internalWebSecure
      name: internalWebSecure
  selector:
    app: traefik
