apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-kgb33-dev
  annotations: 
    argocd-image-updater.argoproj.io/image-list: "blogimg=ghcr.io/kgb33/blog.kgb33.dev:latest"
    argocd-image-updater.argoproj.io/blogimg.update-strategy: digest
spec:
  destination:
    namespace: blog-kgb33-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-apps/blog-kgb33-dev/
    repoURL: https://github.com/KGB33/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
