apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-apps/metalLB
    repoURL: https://github.com/KGB33/ansible.git
    targetRevision: HEAD
    kustomize:
      version: v5.0.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
