apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  source:
    - repoURL: https://github.com/MoJo2600/pihole-kubernetes
      targetRevision: HEAD
      chart: pihole 
      helm:
        releaseName: pihole
        valueFiles: $values/k8s-apps/pihole/values.yaml
    - repoURL: https://github.com/KGB33/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/KGB33/homelab.git
      targetRevision: HEAD
      path: k8s-apps/pihole
      exclude: values.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
