apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roboshpee
  annotations: 
    argocd-image-updater.argoproj.io/image-list: "botimg=ghcr.io/kgb33/roboshpee:latest"
    argocd-image-updater.argoproj.io/botimg.update-strategy: digest
spec:
spec:
  destination:
    namespace: roboshpee
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-apps/roboshpee/
    repoURL: https://github.com/KGB33/homelab.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
