apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-apps/traefik
    repoURL: https://github.com/KGB33/ansible.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
