apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: v28.0.0
      helm:
        valueFiles:
          - $values/k8s-apps/traefik/helm-values.yaml
    # Helm Values
    - repoURL: https://github.com/KGB33/homelab.git
      targetRevision: HEAD
      ref: values
    # Other Config
    - repoURL: https://github.com/KGB33/homelab.git
      path: k8s-apps/blog-kgb33-dev/
      targetRevision: HEAD
