apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: blocky
data:
  config.yaml: |
    upstream:
      default:
        - 1.1.1.1
        - 1.0.0.1
    blocking:
      blackLists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - ads
    ports:
      dns: 53
      http: 4000
    customDNS:
      customTTL: 5m
      filterUnmappedTypes: true
      rewrite:
        local: kgb33.dev
      mapping:
        glint.pve.kgb33.dev: 10.0.9.101
        targe.pve.kgb33.dev: 10.0.9.102
        sundance.pve.kgb33.dev: 10.0.9.103
        ophiuchus.pve.kgb33.dev: 10.0.9.104
        argo.k8s.kgb33.dev: 10.0.8.137
        traefik.k8s.kgb33.dev: 10.0.8.137
        blog.kgb33.dev: 10.0.8.138

