apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.8.53
  labels:
    app: blocky
spec:
  type: LoadBalancer
  ports:
    - port: 53
      name: dns
  selector:
    app: blocky
