---
- name: Configure logind to enable clamshell mode.
  hosts: pve
  become: true
  handlers:
    - name: Restart logind.
      ansible.builtin.service:
        name: systemd-logind
        state: restarted

  tasks:
    - name: Update file
      ansible.builtin.lineinfile:
        path: "/etc/systemd/logind.conf"
        line: "{{ item }}lock"
        regex: "^#?{{ item }}"
      with_items:
        - "HandleLidSwitch="
        - "HandleLidSwitchExternalPower="
        - "HandleLidSwitchDocked="
      notify: Restart logind.
