---
- name: Changes Apt sources Proxmox Enterprize to Free.
  hosts: pve
  become: true

  tasks:
    - name: Update file
      ansible.builtin.lineinfile:
        path: "/etc/apt/sources.list.d/pve-enterprise.list"
        line: "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
