apiVersion: v1
kind: Service
metadata:
  name: blog-kgb33-dev
  labels:
    app: blog-kgb33-dev
spec:
  type: LoadBalancer
  ports:
    - port: 1313
      name: web
  selector:
    app: blog-kgb33-dev
