pve:
  hosts:
    targe.pve.kgb33.dev:
      ansible_host: 10.0.9.102
    sundace.pve.kgb33.dev:
      ansible_host: 10.0.9.103
    glint.pve.kgb33.dev:
      ansible_host: 10.0.9.101

k8s_nodes:
  hosts:
    gnar.kgb33.dev:
    gwen.kgb33.dev:
    sion.kgb33.dev:
    shen.kgb33.dev:
    teemo.kgb33.dev:
    twitch.kgb33.dev:

k8s_routers:
  hosts:
    caster.k8s.kgb33.dev:
      ansible_host: 10.0.9.11
      ansible_connection: network_cli
      ansible_network_os: vyos
      k8s_ip: 10.0.8.11
    melee.k8s.kgb33.dev:
      ansible_host: 10.0.9.12
      ansible_connection: network_cli
      ansible_network_os: vyos
      k8s_ip: 10.0.8.12
    cannon.k8s.kgb33.dev:
      ansible_host: 10.0.9.13
      ansible_connection: network_cli
      ansible_network_os: vyos
      k8s_ip: 10.0.8.13

k8s_route_reflectors:
  hosts:
    super.k8s.kgb33.dev:
      ansible_host: 10.0.9.10
      ansible_connection: network_cli
      ansible_network_os: vyos



vms:
  hosts:
    minecraft.kgb33.dev:
      ansible_host: 10.0.0.147
    mmc.kgb33.dev:
      ansible_host: 10.0.0.168
    taskd:
      ansible_host: 10.0.0.162
    mastodon:
      ansible_host: 10.0.0.166
    blog.kgb33.dev:
      ansible_host: 10.0.0.106

vyos:
  hosts:
    test.vyos.kgb33.dev:
      ansible_host: 10.0.0.179
      ansible_connection: network_cli
      ansible_network_os: vyos
    vyos.kgb33.dev:
      ansible_host: 10.0.0.1
      ansible_connection: network_cli
      ansible_network_os: vyos

rpi:
  hosts:
    rpi-1.kgb33.dev:
      ansible_host: 10.0.3.53
