apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin-password
  namespace: pihole
spec:
  encryptedData:
    pihole-admin-password: AgAQdCxzmyxIXLgkCYNOeB85WJcdEYyu3Y1vwPO6COQxfXMbx5HM2+oDddAnAREMRu7h4ZO4Fw49xbx1u8GtwmNGwxvfqZo1LIxhgrAgoTRc9p6dAhHo0NNHP2gY2oSpCAOsvF72y5YAJaP8sSdxOGVOpwXbPo9bt+4odAFJjR2vnaoIua2qLzv+tHdqU5fgk0bAasMw19iu5XNBpoVV/CVJx9uw5oIeQGYNAbWDx/mfOxalHDdC6vOzIe7ykKLVSKFEOu3j4rSDlS9bi0Vwhf9v9/vf1/7yQnMvqEjmueTd+V1Mcr3cyuW3J56LErj2yZJhrxB285T4Yq0k1p3yhpjEPPuWBMPCfTX35BvCeltjF/7rOoDjvp+V3peI4cKmbKVr2/vtJr0ru/ca7K9DBiyc5miQqNuN+LIaONGj7ZdRI82FqFAptNA6nVFcOTI+OKJr2aLbgzVDKlpdwoWq8hZBKGJfEX2Nck/sKDtCiR9lguC5nqG+UNuXlECmqJl9YTeXOChu4JkxRnpe7q6B1ucb3s2PTvDz/rUKKCHDZk56jAGTOg8076NPQDVcdG19fRtdOZoyw8q/JDoX+uYrb+53pKdAqvXnAPWUFuECO88lejbppxYGrLWb6g9nTAQ3rk0DrHyApe6KKAayBBCmslSf36LkQOzHKt2HDAEcqdm+7KhvWcg4YokGIr/imaqig8EHlW+78hEytso9P0KQmcLq
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin-password
      namespace: pihole

