# vim: ft=yaml.ansible
---
- name: Configure Nat
  hosts: vyos.kgb33.dev

  tasks:
    - name: Configure Source NAT
      vyos.vyos.vyos_config:
        lines:
          - "set nat source rule 100 outbound-interface 'pppoe0'"
          - "set nat source rule 100 source address '10.0.0.0/8'"
          - "set nat source rule 100 translation address 'masquerade'"

    - name: Configure Destination NAT (Port Forwarding)
      vyos.vyos.vyos_config:
        lines:
          # Port Forwarding
          - "set nat destination rule {{ item.port }} description '{{ item.description }}'"
          - "set nat destination rule {{ item.port }} destination port '{{ item.port }}'"
          - "set nat destination rule {{ item.port }} inbound-interface 'pppoe0'"
          - "set nat destination rule {{ item.port }} protocol '{{ item.proto }}'"
          - "set nat destination rule {{ item.port }} translation address '{{ item.address }}'"
      loop:
        - { port: 443, description: "Forward HTTPs to Traefik", proto: "'tcp_udp'", address: "10.0.8.138"}
        - { port: 25566, description: "Forward to modded Minecraft", proto: "'tcp_udp'", address: "10.0.0.11"}
