# vim: ft=yaml.ansible
---
- name: Configure Interfaces
  hosts: vyos.kgb33.dev

  tasks:
    - name: Create vLAN 201 on eth0
      vyos.vyos.vyos_config:
        lines:
          - "set interfaces ethernet eth0 description 'WAN'"
          - "set interfaces ethernet eth0 vif 201"
          - "set interfaces ethernet eth0 hw-id '00:e2:69:4f:f3:5a'"

    - name: Create LAN network on eth1
      vyos.vyos.vyos_config:
        lines:
          - "set interfaces ethernet eth1 address '10.0.3.1/24'"
          - "set interfaces ethernet eth1 description 'LAN'"
          - "set interfaces ethernet eth1 hw-id '00:e2:69:4f:f3:5b'"

    - name: Create HOMELAB network on eth2
      vyos.vyos.vyos_config:
        lines:
          - "set interfaces ethernet eth2 address '10.0.0.1/24'"
          - "set interfaces ethernet eth2 description 'homelab'"
          - "set interfaces ethernet eth2 hw-id '00:e2:69:4f:f3:5c'"

    - name: Load pppoe Authentication
      community.sops.load_vars:
        file: ./files/pppoe_auth.yaml

    - name: Configure PPPoE WAN Interface
      vyos.vyos.vyos_config:
        lines:
          - "set interfaces pppoe pppoe0 authentication password '{{ pppoe_password }}'"
          - "set interfaces pppoe pppoe0 authentication username '{{ pppoe_username }}'"
          - "set interfaces pppoe pppoe0 ip adjust-mss '1452'"
          - "set interfaces pppoe pppoe0 ipv6 address autoconf"
          - "set interfaces pppoe pppoe0 ipv6 adjust-mss '1452'"
          - "set interfaces pppoe pppoe0 local-address '10.0.0.1'"
          - "set interfaces pppoe pppoe0 service-name 'ComcastFiber'"
          - "set interfaces pppoe pppoe0 source-interface 'eth0.201'"
