# vim: ft=yaml.ansible
---
# See https://docs.vyos.io/en/latest/configexamples/autotest/Wireguard/Wireguard.html
- name: Setup Wireguard VPN to HOMELAB
  hosts: vyos.kgb33.dev
  vars:
    vpn_network: "10.10.10.0/24"
    homelab_network: "10.0.0.0/24"
    interface: "wg0"
    port_: 51820

  tasks:
    - name: Load PKI Keys
      community.sops.load_vars:
        file: ./files/wg.yaml

    - name: Create WG Interface
      vars:
        edit_prefix: "set interfaces wireguard wg0"
      vyos.vyos.vyos_config:
        lines:
          - "{{ edit_prefix }} address 10.10.10.1/24"
          - "{{ edit_prefix }} description 'Road-Warrior HOMELAB access.'"
          - "{{ edit_prefix }} port {{ port_ }}"
          - "{{ edit_prefix }} private-key '{{ vyos.prv }}'"
          - "{{ edit_prefix }} peer {{ item.name }} allowed-ips {{ item.addr }}"
          - "{{ edit_prefix }} peer {{ item.name }} public-key '{{ item.pub }}'"
          - "{{ edit_prefix }} peer {{ item.name }} preshared-key '{{ item.psk }}'"
      no_log: true
      with_items:
        - "{{ peers }}"

    - name: Open Wireguard Port
      vyos.vyos.vyos_config:
        lines:
          - "set firewall name WAN-IN rule {{ port_ }} description 'Allow Wireguard'"
          - "set firewall name WAN-IN rule {{ port_ }} action accept"
          - "set firewall name WAN-IN rule {{ port_ }} destination port {{ port_ }}"
          - "set firewall name WAN-IN rule {{ port_ }} protocol 'tcp_udp'"
          - "set firewall name WAN-LOCAL rule {{ port_ }} description 'WireGuard local'"
          - "set firewall name WAN-LOCAL rule {{ port_ }} action 'accept'"
          - "set firewall name WAN-LOCAL rule {{ port_ }} destination port 51820"
          - "set firewall name WAN-LOCAL rule {{ port_ }} log enable"
          - "set firewall name WAN-LOCAL rule {{ port_ }} protocol udp"
          - "set firewall name WAN-LOCAL rule {{ port_ }} source"

    - name: Create Static Route
      vyos.vyos.vyos_config:
        lines:
          - "set protocols static route 10.10.10.0/24 interface wg0"
          - "set protocols static route 10.0.0.0/24 interface wg0"
