# vim: ft=yaml.ansible
---
# See https://docs.vyos.io/en/latest/configexamples/autotest/Wireguard/Wireguard.html
- name: Setup Wireguard VPN to HOMELAB
  hosts: vyos.kgb33.dev
  vars:
    vpn_network: "10.10.10.0/24"
    homelab_network: "10.0.0.0/24"
    interface: "wg0"

  tasks:
    - name: Load PKI Keys
      community.sops.load_vars:
        file: ./files/wg.yaml

    - name: Create WG Interface
      vyos.vyos.vyos_config:
        lines:
          - "set interfaces wireguard {{ interface }} private-key '{{ vyos.prv }}'"
          - "set interfaces wireguard {{ interface }} address 10.10.10.1/24"
          - "set interfaces wireguard {{ interface }} description 'VPN-to-HOMELAB'"
          - "set interfaces wireguard {{ interface }} port 51820"
          - "set interfaces wireguard {{ interface }} peer {{ item.name }} allowed-ips {{ vpn_network }}"
          - "set interfaces wireguard {{ interface }} peer {{ item.name }} allowed-ips {{ homelab_network }}"
          - "set interfaces wireguard {{ interface }} peer {{ item.name }} address {{ item.addr }}"
          - "set interfaces wireguard {{ interface }} peer {{ item.name }} port 51820"
          - "set interfaces wireguard {{ interface }} peer {{ item.name }} public-key {{ item.pub }}"
          - "set interfaces wireguard {{ interface }} peer {{ item.name }} preshared-key {{ item.psk }}"
      no_log: true
      with_items:
        - "{{ peers }}"

    - name: Define WG Route
      vyos.vyos.vyos_config:
        lines:
          - "set protocols static route {{ vpn_network }} interface {{ interface }}"
          - "set protocols static route {{ homelab_network }} interface {{ interface }}"


    - name: Create base WG-IN Firewall rules
      vyos.vyos.vyos_config:
        lines:
          - set firewall name WG-IN default-action drop
          - set firewall name WG-IN rule 10 action accept
          - set firewall name WG-IN rule 10 state established enable
          - set firewall name WG-IN rule 10 state related enable

          - set firewall name WG-IN rule 20 action accept
          - set firewall name WG-IN rule 20 source address 10.10.10.0/24
          - set firewall name WG-IN rule 20 state new enable

          - set firewall interface wg0 in name WG-IN

    - name: Create base WG-LOCAL Firewall rules
      vyos.vyos.vyos_config:
        lines:
          - set firewall name WG-LOCAL default-action drop
          - set firewall name WG-LOCAL rule 10 action accept
          - set firewall name WG-LOCAL rule 10 state established enable
          - set firewall name WG-LOCAL rule 10 state related enable

          - set firewall name WG-LOCAL rule 20 action accept
          - set firewall name WG-LOCAL rule 20 icmp type-name echo-request
          - set firewall name WG-LOCAL rule 20 protocol icmp
          - set firewall name WG-LOCAL rule 20 state new enable

          - set firewall interface wg0 local name WG-LOCAL

    - name: Create Firewall port rules
      vyos.vyos.vyos_config:
        lines:
          - "set firewall name WAN-IN rule 51820 description 'Allow Wireguard'"
          - "set firewall name WAN-IN rule 51820 action accept"
          - "set firewall name WAN-IN rule 51820 destination port 51820"
          - "set firewall name WAN-IN rule 51820 protocol udp"
