apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  entryPoints:
    - lan-web-secure
  routes:
  - match: Host(`dash.k8s.kgb33.dev`)
    kind: Rule
    services:
    - name: kube-prometheus
      namespace: monitoring
      port: 3000
  tls:
    certResolver: letsencrypt
