namespace: monitoring

resources:
  - https://github.com/prometheus-operator/kube-prometheus/manifests/
  - ./ingress.yaml

patches:
  - path: ./grafana_networkpolicy_patch.json
    target:
      kind: NetworkPolicy
      name: grafana
