#ENC[AES256_GCM,data:zmckd+Spmcxwa+7KTBNTUI+4ES5PQwex9ZclLgJUiv3eEow=,iv:1J+iPin8DR7z2b7MZw8SPuVNi682sqIWe329LvmAJDc=,tag:AyxZNOiNZG+Ba+ibbsbNBw==,type:comment]
#ENC[AES256_GCM,data:r4Tob6bcRnflmegwbhzHv5tbikO7frobbD92LknZpshod+fNhabW8wgFFGCuFsAOX/jeGDqkPA==,iv:49I++O/3qwrC83RdV36udPzBQA8O4O4LYfE6ZvLaYWQ=,tag:OXmHJvN2rUupbbJB4QUvVg==,type:comment]
#ENC[AES256_GCM,data:0uaQzkworGA1Lf2Llx5MvdxDCAo0qr/Bi9HyGX0HCDNDNr0fz6mKO7PX1iy+sOCYnA==,iv:cn7sv8IopKtjvYbyxEqj/kTrmxk89I6qEy+69cGSsxI=,tag:tqWO7JoVEWClxTFhRQuZSg==,type:comment]
foo: ENC[AES256_GCM,data:IiGsYIkUo/8zIxwhOwKDTIc3AW6IRj/qq8mSOx3OX8NCY/Un/+FeYma/8Qat6wE=,iv:sI8uLgGlMWW4jhEglt0TJPb9HUxXVHizOHi6NRGGyFw=,tag:hEYD8CUvKkVN4JCbo3ZQbA==,type:str]
sops:
    age:
        - recipient: age1fa5vgl8p2yvjfrllgflun48j3nyff8q7809chsd83lu28r95k55sskzgdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQTlBTHVySjhJU0JSMHBR
            eEduWG5TNEZKWHJKYURrUWcyRmZ6ZDdtUG5ZClYvOUVZN1U3eklRQmUvMlc4VEI4
            aDVWTHZpQS9EV1RMc1RmSUVUalUvVDgKLS0tIE5NRE1ncUkxS1hyUDlnTHZnOW55
            TEF1aUV5SFN5UTd1VXBjRFVoK3lFa1UKVy19Glqwr6sY3IJYDOSnI5XJZD8vkC3Z
            q5e4sJlqJL1Goz/E9cQ2EkJ5n0mCrSmW0GgWBrXUtjA713y2Z6P3ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T18:25:52Z"
    mac: ENC[AES256_GCM,data:d55HaUcF9y89waS9a7URLY1f7f06sfbLanPbjl6+8y8E0YYY5FDZbu03OAUQqVNpsVG4AjtOjpuqjZ+4Aeoju6srNhRDmPlG+hqhjbexNySQVpAwU7NQlSBjLh2QLDbmlUIPV5y71Y/FxAVbCcZsOzE9/troF+pIcPgdzyqHBwU=,iv:tmyJlWorI9SeN6cg2o6tbB1qIs4wkjbAcxt9sbzZuDo=,tag:+o2sa1CeCiXEcSLyh4EuFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
